---
- name: Install unzip
  apt:
    name: unzip
    state: present
  tags: consul

- name: Make consul directories
  file:
    path: "/opt/{{ item }}"
    owner: root
    group: root
    mode: 0755
    recurse: no
    state: directory
  with_items: ["consul/bin", "consul/config", "consul/data"]
  tags: consul

- name: copy acl.json
  template: src=acl.json.j2 dest=/opt/consul/config/acl.json
  notify: reload consul
  tags: consul

- name: copy config.json
  template: src=config.json.j2 dest=/opt/consul/config/config.json
  notify: reload consul
  tags: consul

- name: copy consul.service
  copy: src=consul.service dest=/etc/systemd/system/consul.service mode=0540
  notify: reload consul
  tags: consul

- name: Install Consul
  shell: |
    cd /opt/consul/bin/
    [[ `find . -name "*.zip"` ]] && rm `find . -name "*.zip"`
    wget https://releases.hashicorp.com/consul/{{ consulVersion }}/consul_{{ consulVersion }}_linux_amd64.zip -O /opt/consul/bin/consul_{{ consulVersion }}_linux_amd64.zip
    unzip -o /opt/consul/bin/consul_{{ consulVersion }}_linux_amd64.zip
    chmod +x consul
  args:
    creates: /opt/consul/bin/consul_{{ consulVersion }}_linux_amd64.zip
  notify: restart consul
  tags: consul

- name: Ensure consul started
  service: name=consul state=started
  tags: consul
