---

- name: dgraphZero
  docker_container:
    name: dgraphZero
    image: dgraph/dgraph
    state: started
    recreate: no
    command: "{{ zeroCommand }}"
    published_ports:
      - "{{ port1 }}"
      - "{{ port2 }}"
    volumes:
      - /datadisk/dgraph:/dgraph
  tags: dgraphZero