---
- name: Docker run mongodb
  docker_container:
    name: mongodb
    hostname: mongodb
    image: mongo@sha256:fbb95eaa5a0c84d0d2098775f166003c568a79f993d91309cee7cda4135bbbfd
    state: started
    recreate: no
    published_ports:
      - 27017:27017
  tags: mongodb
