---
- name: Docker run learning locker API
  docker_container:
    name: api-server
    hostname: api-server
    image: cshr/lpg-learning-locker:d29392f370a186af9d9338fbe796e7d60c32fcd91bf23824c0fd86b6237fcd96
    state: started
    command: node /opt/learning-locker/api/dist/server
    links:
      - mailhog:mailhog
    published_ports:
      - 8082:8082
    recreate: no
    env:
      MONGO_URL: mongodb://{{ mongodb_host }}/learninglocker
      MONGODB_PATH: mongodb://{{ mongodb_host }}/learninglocker
      REDIS_HOST: "{{ redis_host }}"
      REDIS_URL: redis://{{ redis_host }}:6379/0
  tags: learning-locker,app-container

- name: Docker run learning locker UI
  docker_container:
    name: ui
    hostname: ui
    image: cshr/lpg-learning-locker:d29392f370a186af9d9338fbe796e7d60c32fcd91bf23824c0fd86b6237fcd96
    state: started
    command: node /opt/learning-locker/ui/dist/server
    links:
      - mailhog:mailhog
      - api-server:api-server
    published_ports:
      - 3000:3000
    recreate: no
    env:
      API_HOST: api-server
      VIRTUAL_HOST: lrs{{ envDomain }}.cshr.digital
      VIRTUAL_PORT: 3000
      LETSENCRYPT_HOST: lrs{{ envDomain }}.cshr.digital
      LETSENCRYPT_EMAIL: silvanod@kainos.com
      MONGO_URL: mongodb://{{ mongodb_host }}/learninglocker
      MONGODB_PATH: mongodb://{{ mongodb_host }}/learninglocker
      REDIS_HOST: "{{ redis_host }}"
      REDIS_URL: redis://{{ redis_host }}:6379/0
  tags: learning-locker-admin,app-container

- name: Docker run learning locker setup
  docker_container:
    name: setup
    hostname: setup
    image: cshr/lpg-learning-locker:d29392f370a186af9d9338fbe796e7d60c32fcd91bf23824c0fd86b6237fcd96
    state: stopped
    command: /opt/learning-locker/./node_modules/.bin/babel-node /opt/learning-locker/mkadmin.js
    recreate: no
    env:
      NODE_PATH: /opt/learning-locker
      MONGO_URL: mongodb://{{ mongodb_host }}/learninglocker
      MONGODB_PATH: mongodb://{{ mongodb_host }}/learninglocker
      REDIS_HOST: "{{ redis_host }}"
      REDIS_URL: redis://{{ redis_host }}:6379/0
  tags: learning-locker-admin,app-container
