sudo: required
dist: trusty
language: python
python: '2.7'

install:
- pip install ansible
- sudo apt-get install coreutils

script:
- chmod +x envVar.py
- echo $mvp_test | base64 -d | ./envVar.py  > mvp_test
- chmod 600 mvp_test
- echo $vaultpassword | base64 -d | ./envVar.py > vault.yml
- cat ssh_$TRAVIS_BRANCH.conf >> ~/.ssh/config
- ansible-playbook site.yml -i environments/test
- rm -f mvp_test
- rm -f vault.yml

addons:
  ssh_known_hosts:
  - prod-lpg.uksouth.cloudapp.azure.com
  - test-lpg.uksouth.cloudapp.azure.com
  - 10.0.10.4
  - 10.0.11.4
  - 10.0.12.4