---
sudo: required
dist: trusty

language: python
python: "2.7"

install:
  - pip install ansible

script:
  - echo $vaultPassword > vault.yml
  - ansible-vault decrypt mvp_test
  - ansible-playbook site.yml -i environments/test -t wso2 --ask-vault-pass $vaultPassword