---
#install docker and mount disk on all hosts
- hosts: mvp
  become: true
  gather_facts: false
  roles:
    - docker
    - datadisk

#run containers on host data-01
- hosts: mvp[2]
  become: true
  gather_facts: false
  roles:
    - dgraph
    - postgres
    - mongodb
    - redis

#run containers on host app-01
- hosts: mvp[1]
  become: true
  gather_facts: false
  roles:

#run containers on host public-01
- hosts: mvp[0]
  become: true
  gather_facts: false
  roles:
    - mailhog
    - wso2
    - learning-locker
    - lpg-ui
    - nginx



