---
#install docker and mount disk on all hosts
- hosts: mvp
  become: true
  gather_facts: false
  roles:
    - docker
    - datadisk

#run containers on host data-01
- hosts: mvp[2]
  become: true
  gather_facts: false
  roles:
    - elasticsearch
    - postgres
    - mongodb
    - redis
  vars:
    host: localhost

#run containers on host app-01
- hosts: mvp[1]
  become: true
  gather_facts: false
  roles:
    - mailhog
    - learning-locker-admin
    - learning-locker-app
    - lpg-learner-record
    - lpg-learning-catalogue
    - xapi

#run containers on host public-01
- hosts: mvp[0]
  become: true
  gather_facts: false
  roles:
    - wso2
    - lpg-ui
    - lpg-management-ui
    - nginx
    - xapi