---

- hosts: dgraph
  become: true
  gather_facts: true
  roles:
    - docker
    - hosts
    - dataDisk
    - filebeat

#### dgraph Zero

- hosts: dgraph[0]
  become: true
  gather_facts: false
  roles:
    - dgraphZero
  vars:
    zeroCommand: "dgraph zero -o -2000 --my=dgraph-01:5080 --replicas 3 --idx 1"
    port: "5080:5080"

- hosts: dgraph[1]
  become: true
  gather_facts: false
  roles:
    - dgraphZero
  vars:
    zeroCommand: "dgraph zero -o -1999 --my=dgraph-02:5081 --replicas 3 --peer dgraph-01:5080 --idx 2"
    port: "5081:5081"

- hosts: dgraph[2]
  become: true
  gather_facts: false
  roles:
    - dgraphZero
  vars:
    zeroCommand: "dgraph zero -o -1998 --my=dgraph-03:5082 --replicas 3 --peer dgraph-01:5080 --idx 3"
    port: "5082:5082"

#### dgraph Server

- hosts: dgraph[0]
  become: true
  gather_facts: false
  roles:
    - dgraphServer
  vars:
    serverCommand: "dgraph server --my=dgraph-01:7080 --memory_mb=1048 --zero=dgraph-01:5080"
    port1: "7080:7080"
    port2: "8080:8080"

- hosts: dgraph[1]
  become: true
  gather_facts: false
  roles:
    - dgraphServer
  vars:
    serverCommand: "dgraph server --my=dgraph-02:7081 --memory_mb=1048 --zero=dgraph-01:5080 -o 1"
    port1: "7081:7081"
    port2: "8080:8081"

- hosts: dgraph[2]
  become: true
  gather_facts: false
  roles:
    - dgraphServer
  vars:
    serverCommand: "dgraph server --my=dgraph-03:7082 --memory_mb=1048 --zero=dgraph-01:5080 -o 2"
    port1: "7082:7082"
    port2: "8080:8082"





