---
- name: Docker run lpg-management-ui
  docker_container:
    name: lpg-management-ui
    hostname: lpg-management-ui
    image: cshr/lpg-services-management:{{ lpgservices }}
    state: started
    command: "node ../node_modules/management-ui/server.js"
    working_dir: /var/www/app/dist/management-ui
    recreate: no
    env:
      XAPI_URL: http://{{ xapi_host }}/data/xAPI
      VIRTUAL_HOST: admin{{ envDomain }}.cshr.digital
      LETSENCRYPT_HOST: admin{{ envDomain }}.cshr.digital
      LETSENCRYPT_EMAIL: silvanod@kainos.com
      AUTHENTICATION_SERVICE_URL: http://identity{{ envDomain }}.cshr.digital
      ENV_PROFILE: "{{env}}"
  tags: lpg-management-ui,lpgservices,app-container
