---
- name: Install unzip
  apt:
    name: unzip
    state: present
  tags: vault

- name: Make vault directories
  file:
    path: "/opt/{{ item }}"
    owner: root
    group: root
    mode: 0755
    recurse: no
    state: directory
  with_items: ["vault/bin", "vault/config", "vault/data"]
  tags: vault

- name: copy vault.service
  copy: src=vault.service dest=/etc/systemd/system/vault.service mode=0540
  notify: reload vault
  tags: vault

- name: Install vault
  shell: |
    cd /opt/vault/bin/
    [[ `find . -name "*.zip"` ]] && rm `find . -name "*.zip"`
    wget https://releases.hashicorp.com/vault/{{ vaultVersion }}/vault_{{ vaultVersion }}_linux_amd64.zip -O /opt/vault/bin/vault_{{ vaultVersion }}_linux_amd64.zip
    unzip -o /opt/vault/bin/vault_{{ vaultVersion }}_linux_amd64.zip
    chmod +x vault
  args:
    creates: /opt/vault/bin/vault_{{ vaultVersion }}_linux_amd64.zip
  notify: restart vault
  tags: vault

- name: Ensure vault started
  service: name=vault state=started
  tags: vault



