---
- name: Check token exits
  stat:
    path: environments/{{ env }}/group_vars/tokens/standardToken.yml
  register: token
  tags: token

- name: copy template token.sh
  template: src=token.sh.j2 dest=/tmp/token.sh mode=0744
  when: not token.stat.exists
  tags: token

- name: generate "{{ item }}"Token
  command: /tmp/token.sh "{{ item }}"
  when: not token.stat.exists
  with_items:
    - standard
    - secure
  tags: token

- name: delete token.sh
  file: path='/tmp/token.sh' state=absent
  when: not token.stat.exists
  tags: token