---
- name: Docker run lpg-learner-ui
  docker_container:
    name: lpg-ui
    hostname: lpg-learner-ui
    image: superroot/lpg-learner-ui:{{ lpglearnerui }}
    state: started
    recreate: no
    env:
      VIRTUAL_HOST: lpg.test.cshr.digital
      LETSENCRYPT_HOST: lpg.test.cshr.digital
      LETSENCRYPT_EMAIL: silvanod@kainos.com
  tags: lpg-ui




