---

- name: dgraphServer
  docker_container:
    name: dgraphServer
    image: dgraph/dgraph
    state: started
    recreate: no
    command: "{{ serverCommand }}"
    published_ports:
      - "{{ port1 }}"
      - "{{ port2 }}"
    volumes:
      - /datadisk/dgraph:/dgraph
      - /etc/hosts.ansible:/etc/hosts
  become: yes
  tags: dgraphServer
