---
- name: Docker run wso2
  docker_container:
    name: lpg-wso2
    hostname: lpg-wso2
    image: cshr/lpg-wso2-is:{{ wso2is }}
    state: started
    recreate: no
    env:
      DATABASE_URL: jdbc:postgresql://data-01:5432/wso2is
      DATABASE_USER: "{{ db_user }}"
      DATABASE_PASSWORD: "{{ db_password }}"
      CARBON_PROTOCOL: https
      CARBON_HOST: identity{{ envDomain }}.cshr.digital
      CARBON_PORT : 443
      LPG_UI_URL: https://lpg{{ envDomain }}.cshr.digital
      VIRTUAL_HOST: identity{{ envDomain }}.cshr.digital
      VIRTUAL_PROTO: https
      VIRTUAL_PORT: 9443
      LETSENCRYPT_HOST: identity{{ envDomain }}.cshr.digital
      LETSENCRYPT_EMAIL: silvanod@kainos.com
  tags: wso2,app




