---
- name: Create docker dgraph network
  docker_network:
    name: dgraph
  tags: dgraph

- name: Docker run dgraph zero
  docker_container:
    name: dgraphzero
    hostname: dgraphzero
    image: dgraph/dgraph
    state: started
    command: dgraph zero --port_offset -2000 --my=dgraphzero:5080
    networks:
      - name: dgraph
    published_ports:
      - 5080:5080
    recreate: no
  tags: dgraph

- name: Docker run dgraph server
  docker_container:
    name: dgraphserver
    hostname: dgraphserver
    image: dgraph/dgraph
    state: started
    command: dgraph server --my=dgraphserver:7080 --memory_mb=1048 --zero=dgraphzero:5080
    networks:
      - name: dgraph
    published_ports:
      - 7080:7080
      - 8080:8080
      - 8080:8080
    recreate: no
  tags: dgraph

- name: Docker run dgraph ui
  docker_container:
    name: dgraphui
    image: dgraph/dgraph
    state: started
    command: dgraph-ratel -port 8081
    published_ports:
      - 8081:8081
    recreate: no
  tags: dgraph