---
- name: Docker run lpg-ui
  docker_container:
    name: lpg-ui
    hostname: lpg-ui
    image: cshr/lpg-services:{{ lpgservices }}
    state: started
    recreate: no
    env:
      VIRTUAL_HOST: lpg{{ envDomain }}.cshr.digital
      LETSENCRYPT_HOST: lpg{{ envDomain }}.cshr.digital
      LETSENCRYPT_EMAIL: silvanod@kainos.com
      AUTHENTICATION_SERVICE_URL: https://identity{{ envDomain }}.cshr.digital
      DGRAPH_ENDPOINT: data-01:9080
  tags: lpg-ui,lpgservices