---
- name: Docker run lpg-ui
  docker_container:
    name: lpg-ui
    hostname: lpg-ui
    image: cshr/lpg-ui:{{ lpgui }}
    state: started
    recreate: no
    env:
      VIRTUAL_HOST: lpg{{ envDomain }}.cshr.digital
      LETSENCRYPT_HOST: lpg{{ envDomain }}.cshr.digital
      LETSENCRYPT_EMAIL: silvanod@kainos.com
      AUTHENTICATION_SERVICE_URL: https://identity{{ envDomain }}.cshr.digital
      DGRAPH_ENDPOINT: data-test-lpg.uksouth.cloudapp.azure.com:9080
  tags: lpg-ui




