---
- name: Docker run lpg-ui
  docker_container:
    name: lpg-ui
    hostname: lpg-ui
    image: cshr/lpg-services:{{ lpgservices }}
    state: started
    command: "node ../node_modules/ui/server.js"
    working_dir: /var/www/app/dist/ui
    recreate: no
    env:
      XAPI_URL: http://{{ xapi_host }}/data/xAPI
      LEARNER_RECORD_SERVICE_URL: http://{{ learnerRecordHost }}
      VIRTUAL_HOST: lpg{{ envDomain }}.cshr.digital
      LETSENCRYPT_HOST: lpg{{ envDomain }}.cshr.digital
      LETSENCRYPT_EMAIL: silvanod@kainos.com
      AUTHENTICATION_SERVICE_URL: https://identity{{ envDomain }}.cshr.digital
      DGRAPH_ENDPOINT: data-01:9080
      AWS_ACCESS_KEY_ID: '{{ awsAccessKeyId }}'
      AWS_SECRET_ACCESS_KEY: '{{ awsSecretAccessKey }}'
  tags: lpg-ui,lpgservices

