---
- name: Copy .htpasswd
  copy:
    src: .htpasswd
    dest: /opt/htpasswd
    mode: 0440
  tags: lpg-ui

- name: Docker run lpg-ui
  docker_container:
    name: lpg-ui
    hostname: lpg-ui
    image: cshr/lpg-ui:{{ lpgui }}
    state: started
    recreate: no
    volumes:
      - /opt/htpasswd:/etc/nginx/htpasswd
    env:
      VIRTUAL_HOST: lpg{{ envDomain }}.cshr.digital
      LETSENCRYPT_HOST: lpg{{ envDomain }}.cshr.digital
      LETSENCRYPT_EMAIL: silvanod@kainos.com
      AUTHENTICATION_SERVICE_URL: https://identity{{ envDomain }}.cshr.digital
      DGRAPH_ENDPOINT: data-01:9080
  tags: lpg-ui,app




]]