---

- name: create /datadisk directory
  file:
    path: /datadisk
    owner: root
    group: root
    mode: 0744
    state: directory
  tags: disk

- name: Create filesystem
  filesystem:
    fstype: ext4
    dev: /dev/sdb1
  tags: disk

- name: Mount device
  mount:
    path: /datadisk
    src: /dev/sdb1
    fstype: ext4
    state: mounted
  tags: disk