---
- name: Docker run lpg-learner-record
  docker_container:
    name: lpg-learner-record
    hostname: lpg-learner-record
    image: cshr/lpg-learner-record:{{ lpglearnerrecord }}
    state: started
    recreate: no
    ports:
      - 9000:9000
    env:
      AUTH_USER: "user"
      AUTH_PASSWORD: "password"
      XAPI_URL: http://{{ xapi_host }}/data/xAPI
      XAPI_USERNAME: 66f2b4fc001e3da992d23b57d8a7457655bea078
      XAPI_PASSWORD: 1c0e1b6827606d7efed71e204939d048f94f842b
  tags: lpg-learner-record,lpglearnerrecord,app-container
