---
- name: Docker run lpg-learner-record
  docker_container:
    name: lpg-learner-record
    hostname: lpg-learner-record
    image: cshr/lpg-learner-record:{{ lpg-learner-record }}
    state: started
    recreate: no
    ports:
      - 9000:9000
    env:
      XAPI_URL: http://{{ xapi_host }}/data/xAPI
      XAPI_AUTHORISATION: NjZmMmI0ZmMwMDFlM2RhOTkyZDIzYjU3ZDhhNzQ1NzY1NWJlYTA3ODoxYzBlMWI2ODI3NjA2ZDdlZmVkNzFlMjA0OTM5ZDA0OGY5NGY4NDJi
  tags: lpg-learner-record,lpglearnerrecord,app-container
