---
- name: Docker run wso2
  docker_container:
    name: lpg-wso2-local
    hostname: lpg-wso2-local
    image: cshr/lpg-wso2-is:{{ wso2is }}
    state: started
    recreate: no
    env:
      DATABASE_URL: jdbc:postgresql://{{ wso2_database_host }}/wso2is
      DATABASE_USER: "{{ db_user }}"
      DATABASE_PASSWORD: "{{ db_password }}"
      CARBON_PROTOCOL: https
      CARBON_HOST: identity.local.cshr.digital
      CARBON_PORT : 443
      LPG_UI_URL: https://lpg.local.cshr.digital
      LPG_MANAGEMENT_UI_URL: https://admin.local.cshr.digital
      VIRTUAL_HOST: identity.local.cshr.digital
      VIRTUAL_PROTO: https
      VIRTUAL_PORT: 9443
      LETSENCRYPT_HOST: identity.local.cshr.digital
      LETSENCRYPT_EMAIL: silvanod@kainos.com
  tags: wso2is-local
