---
- name: Docker run learning locker API worker
  docker_container:
    name: api-worker
    hostname: api-worker
    image: cshr/lpg-learning-locker:d29392f370a186af9d9338fbe796e7d60c32fcd91bf23824c0fd86b6237fcd96
    state: started
    command: node /opt/learning-locker/worker/dist/server
    links:
      - mailhog:mailhog
    recreate: no
    env:
      MONGO_URL: mongodb://{{ mongodb_host }}/learninglocker
      MONGODB_PATH: mongodb://{{ mongodb_host }}/learninglocker
      REDIS_HOST: "{{ redis_host }}"
      REDIS_URL: redis://{{ redis_host }}:6379/0
  tags: learning-locker-app,app-container

- name: Docker run learning locker xAPI
  docker_container:
    name: xapi
    hostname: xapi
    image: cshr/lpg-learning-locker:d29392f370a186af9d9338fbe796e7d60c32fcd91bf23824c0fd86b6237fcd96
    state: started
    command: node /opt/xapi-service/dist/server
    links:
      - mailhog:mailhog
    published_ports:
      - 8083:8083
    recreate: no
    env:
      MONGO_URL: mongodb://{{ mongodb_host }}/learninglocker
      MONGODB_PATH: mongodb://{{ mongodb_host }}/learninglocker
      REDIS_HOST: "{{ redis_host }}"
      REDIS_URL: redis://{{ redis_host }}:6379/0
  tags: learning-locker-app,app-container


