---
- name: Run Nginx proxy Container
  docker_container:
    name: nginxProxy
    image: jwilder/nginx-proxy
    volumes : /var/run/docker.sock:/tmp/docker.sock:ro
    state: started
    recreate: no
    published_ports:
      - 80:80
  become: yes
  tags : proxy


#https://github.com/jwilder/nginx-proxy

#http://docs.ansible.com/ansible/latest/docker_container_module.html#docker-container